import math    #导入math模块
print ("acos(0.64) : ", math.acos(0.64))
print ("acos(0) : ",  math.acos(0))
print ("asin(-1) : ",  math.asin(-1))
print ("asin(1) : ",  math.asin(1))
print ("atan(0) : ",  math.atan(0))
print ("atan(10) : ",  math.atan(10))
print ("atan2(5，5) : ",  math.atan2(5,5))
print ("atan2(-10，10) : ",  math.atan2(-10,10))
print ("cos(3) : ",  math.cos(3))
print ("cos(-3) : ",  math.cos(-3))
print ("hypot(3， 2) : ",  math.hypot(3, 2))
print ("hypot(-3， 3) : ",  math.hypot(-3, 3))
print ("sin(3) : ",  math.sin(3))
print ("sin(-3) : ",  math.sin(-3))
print ("(tan(3) : ",  math.tan(3))
print ("tan(-3) : ",  math.tan(-3))
print ("degrees(3) : ",  math.degrees(3))
print ("degrees(-3) : ",  math.degrees(-3))
print ("radians(3) : ",  math.radians(3))
print ("radians(-3) : ",  math.radians(-3))
