tuple1 = (5, 4, 8,12,16,38)
print("元组中的初始元素数据：",tuple1)
print("元组中元素的最大值：",max(tuple1))
print("元组中元素的最小值：",min(tuple1))
print("元组中元素的个数：",len(tuple1))
print("把元组转换成列表，并显示：",list(tuple1))
print("把列表为元组，并显示：",tuple(list(tuple1)))
