list1 = ['Google', 'Runoob', 'Taobao', 'Baidu']
list2 = list1.copy()
print ("list2 列表: ", list2)
print()
list2.sort()
print ("list2列表排序后 : ", list2)
print()
list2.reverse()
print ("list2列表反转后: ", list2)
print()
list2.remove('Taobao')
print ("list2列表移除Taobao后 : ", list2)
print()
list2.pop()
print ("list2列表再移除最后一个元素 : ", list2)
print()
list2.insert(1, 'Runoob')
print ('列表插入元素后为 : ', list2)
print ('Runoob 索引值为', list2.index('Runoob'))
print()
list2.clear()
print ("列表清空后 : ", list2)
